sudo: false

language: node_js

node_js:
  - '10'
  - '12'
  - '14'
  - '16'

branches:
  only:
    - master
    - travis-ci

# Not using `npm install --dev` because it is recursive. It will pull in the all
# development dependencies for CoffeeScript. Way too much spew in the Travis CI
# build output.

before_install:
  - for dir in hash.*; do (cd $dir && npm install --no-save --no-package-lock); done
  - npm install --no-save --no-package-lock
  - npm install -g nyc node-gyp prove

script:
  - nyc npm test
