#!/bin/sh

set -e

rm -rf coverage

count=1;
for file in $(find hash.* -name \*.t.js); do
  echo "$file" | grep '/sha1.t.js' > /dev/null && continue
  NODE_PATH=. istanbul cover -x 'proof.js' -x '*/t/**' $file > /dev/null 2>&1
  mv coverage/coverage.json coverage/coverage$count.json
  count=$(expr $count + 1)
done

istanbul report --root coverage --dir coverage > /dev/null

sed -i -e s,'^SF:'`pwd`/,SF:, coverage/lcov.info

exit 0
